//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public string BR_ID { get; set; }
        public string Quantity { get; set; }
        public string Supplier { get; set; }
        public string SupplierNotes { get; set; }
        public string UserID { get; set; }
    
        public virtual DRUG DRUG { get; set; }
    }
}
