//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int TransactionId { get; set; }
        public string BR_ID { get; set; }
        public string No_Item { get; set; }
        public string TotalPrice { get; set; }
        public decimal Selling_Price { get; set; }
        public System.DateTime Sale_Date { get; set; }
        public string UserID { get; set; }
    
        public virtual DRUG DRUG { get; set; }
    }
}
